services:
  frontend:
    build:
      context: frontend
      target: development
    networks:
      - client-side
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src:ro
    env_file:
      - fe.env
    restart: always

  backend:
    build:
      context: backend
      target: development
    networks:
      - client-side
      - server-side
    volumes:
      - ./backend/src:/code/src
      - backend-cache:/code/target
    depends_on:
      - db
    env_file:
      - be.env
    restart: always

  db:
    image: postgres:17-alpine
    networks:
      - server-side
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - db.env
    restart: always

networks:
  client-side: {}
  server-side: {}

volumes:
  backend-cache: {}
  db-data: {}
